# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green apple" --output-path "lerf_masks/figurines/green apple"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green toy chair" --output-path "lerf_masks/figurines/green toy chair"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "old camera" --output-path "lerf_masks/figurines/old camera"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "porcelain hand" --output-path "lerf_masks/figurines/porcelain hand"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "red apple" --output-path "lerf_masks/figurines/red apple"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "red toy chair" --output-path "lerf_masks/figurines/red toy chair"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "rubber duck with red hat" --output-path "lerf_masks/figurines/rubber duck with red hat"

CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the yellow fruit" --output-path "ovs3d_masks/bed_reasoning/banana"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which can be worn on the foot" --output-path "ovs3d_masks/bed_reasoning/black leather shoe"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which can be used to take photos" --output-path "ovs3d_masks/bed_reasoning/camera"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the part of person, excluding other objects" --output-path "ovs3d_masks/bed_reasoning/hand"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is red and leather" --output-path "ovs3d_masks/bed_reasoning/red bag"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "where is a good place to lie down" --output-path "ovs3d_masks/bed_reasoning/white sheet"

CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "banana" --output-path "ovs3d_masks/bed/banana"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "black leather shoe" --output-path "ovs3d_masks/bed/black leather shoe"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "camera" --output-path "ovs3d_masks/bed/camera"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "hand" --output-path "ovs3d_masks/bed/hand"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "red bag" --output-path "ovs3d_masks/bed/red bag"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/bed/lerf/2024-08-30_120318/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "white sheet" --output-path "ovs3d_masks/bed/white sheet"

# ns-viewer --load-config outputs/bed/lerf/2024-08-30_120318/config.yml
