# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green apple" --output-path "lerf_masks/figurines/green apple"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green toy chair" --output-path "lerf_masks/figurines/green toy chair"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "old camera" --output-path "lerf_masks/figurines/old camera"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "porcelain hand" --output-path "lerf_masks/figurines/porcelain hand"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "red apple" --output-path "lerf_masks/figurines/red apple"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "red toy chair" --output-path "lerf_masks/figurines/red toy chair"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "rubber duck with red hat" --output-path "lerf_masks/figurines/rubber duck with red hat"

CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "what is a white animal doll" --output-path "messy_rooms_masks/large_corridor_25/what is a white animal doll"
# CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is bottle shaped" --output-path "messy_rooms_masks/large_corridor_25/which is bottle shaped"
# CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is box with fruit patterns printed on it" --output-path "messy_rooms_masks/large_corridor_25/which is box with fruit patterns printed on it"
# CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is bucket shaped,made of plastic" --output-path "messy_rooms_masks/large_corridor_25/which is bucket shaped,made of plastic"
# CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is gray and square,you can put things in it" --output-path "messy_rooms_masks/large_corridor_25/which is gray and square,you can put things in it"


# CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "what is a white animal doll" --output-path "messy_rooms_masks/large_corridor_25/what is a white animal doll"
# CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is bottle shaped" --output-path "messy_rooms_masks/large_corridor_25/which is bottle shaped"
# CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is box with fruit patterns printed on it" --output-path "messy_rooms_masks/large_corridor_25/which is box with fruit patterns printed on it"
# CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is bucket shaped,made of plastic" --output-path "messy_rooms_masks/large_corridor_25/which is bucket shaped,made of plastic"
# CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is gray and square,you can put things in it" --output-path "messy_rooms_masks/large_corridor_25/which is gray and square,you can put things in it"

# ns-viewer --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml
