# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green apple" --output-path "lerf_masks/figurines/green apple"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green toy chair" --output-path "lerf_masks/figurines/green toy chair"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "old camera" --output-path "lerf_masks/figurines/old camera"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "porcelain hand" --output-path "lerf_masks/figurines/porcelain hand"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "red apple" --output-path "lerf_masks/figurines/red apple"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "red toy chair" --output-path "lerf_masks/figurines/red toy chair"
# ns-render dataset --load-config outputs/figurines/lerf/2024-08-22_111841/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "rubber duck with red hat" --output-path "lerf_masks/figurines/rubber duck with red hat"


# large_corridor_25
CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green pot" --output-path "messy_rooms_masks/large_corridor_25/green pot"
CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "white plush doll" --output-path "messy_rooms_masks/large_corridor_25/white plush doll"
CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "white bottle" --output-path "messy_rooms_masks/large_corridor_25/white bottle"
CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "brown bowl" --output-path "messy_rooms_masks/large_corridor_25/brown bowl"
CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "blue lunch box" --output-path "messy_rooms_masks/large_corridor_25/blue lunch box"

CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green pot" --output-path "messy_rooms_masks/large_corridor_25/green pot"
CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "white plush doll" --output-path "messy_rooms_masks/large_corridor_25/white plush doll"
CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "white bottle" --output-path "messy_rooms_masks/large_corridor_25/white bottle"
CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "brown bowl" --output-path "messy_rooms_masks/large_corridor_25/brown bowl"
CUDA_VISIBLE_DEVICES=0 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "blue lunch box" --output-path "messy_rooms_masks/large_corridor_25/blue lunch box"

CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is an object used for planting" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is an object used for planting"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is an object used for comfort" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is an object used for comfort"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is an white bottle-shaped object" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is an white bottle-shaped object"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a brown object that can be used for eating" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is a brown object that can be used for eating"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a blue object with dinosaur print" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is a blue object with dinosaur print"

CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is an object used for planting" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is an object used for planting"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is an object used for comfort" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is an object used for comfort"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is an white bottle-shaped object" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is an white bottle-shaped object"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a brown object that can be used for eating" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is a brown object that can be used for eating"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/large_corridor_25/lerf/2024-09-04_121137/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a blue object with dinosaur print" --output-path "messy_rooms_masks/large_corridor_25_reasoning/which is a blue object with dinosaur print"

# large_corridor_50
CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "black and white shoe" --output-path "messy_rooms_masks/large_corridor_50/black and white shoe"
CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "blue bag" --output-path "messy_rooms_masks/large_corridor_50/blue bag"
CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "wooden box" --output-path "messy_rooms_masks/large_corridor_50/wooden box"
CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "black cable" --output-path "messy_rooms_masks/large_corridor_50/black cable"
CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "colorful clock" --output-path "messy_rooms_masks/large_corridor_50/colorful clock"

CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "black and white shoe" --output-path "messy_rooms_masks/large_corridor_50/black and white shoe"
CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "blue bag" --output-path "messy_rooms_masks/large_corridor_50/blue bag"
CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "wooden box" --output-path "messy_rooms_masks/large_corridor_50/wooden box"
CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "black cable" --output-path "messy_rooms_masks/large_corridor_50/black cable"
CUDA_VISIBLE_DEVICES=2 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "colorful clock" --output-path "messy_rooms_masks/large_corridor_50/colorful clock"

CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a black and white object that can be worn on the feet" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a black and white object that can be worn on the feet"
CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a blue object used for carrying items with balls patterns on it" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a blue object used for carrying items with balls patterns on it"
CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a brown object used for storing and organizing items" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a brown object used for storing and organizing items"
CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a black object used for connecting electronic devices" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a black object used for connecting electronic devices"
CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a colorful object used for telling time" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a colorful object used for telling time"

CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a black and white object that can be worn on the feet" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a black and white object that can be worn on the feet"
CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a blue object used for carrying items with balls patterns on it" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a blue object used for carrying items with balls patterns on it"
CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a brown object used for storing and organizing items" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a brown object used for storing and organizing items"
CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a black object used for connecting electronic devices" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a black object used for connecting electronic devices"
CUDA_VISIBLE_DEVICES=3 ns-render dataset --load-config outputs/large_corridor_50/lerf/2024-09-06_161433/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a colorful object used for telling time" --output-path "messy_rooms_masks/large_corridor_50_reasoning/which is a colorful object used for telling time"

# large_corridor_100
CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a white object that can be worn on the feet" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a white object that can be worn on the feet"
CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a blue and yellow object that can be worn on the feet" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a blue and yellow object that can be worn on the feet"
CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a blue and white object that can be used for wiping" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a blue and white object that can be used for wiping"
CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a green object with holes that can be used for storage" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a green object with holes that can be used for storage"
CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a red and blue object appearing in games" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a red and blue object appearing in games"

CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a white object that can be worn on the feet" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a white object that can be worn on the feet"
CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a blue and yellow object that can be worn on the feet" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a blue and yellow object that can be worn on the feet"
CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a blue and white object that can be used for wiping" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a blue and white object that can be used for wiping"
CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a green object with holes that can be used for storage" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a green object with holes that can be used for storage"
CUDA_VISIBLE_DEVICES=4 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is a red and blue object appearing in games" --output-path "messy_rooms_masks/large_corridor_100_reasoning/which is a red and blue object appearing in games"
                            
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "white and black shoe" --output-path "messy_rooms_masks/large_corridor_100/white and black shoe"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "blue and yellow sandal" --output-path "messy_rooms_masks/large_corridor_100/blue and yellow sandal"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "blue and white striped towel" --output-path "messy_rooms_masks/large_corridor_100/blue and white striped towel"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green plastic box" --output-path "messy_rooms_masks/large_corridor_100/green plastic box"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "red and blue doll" --output-path "messy_rooms_masks/large_corridor_100/red and blue doll"

CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "white and black shoe" --output-path "messy_rooms_masks/large_corridor_100/white and black shoe"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "blue and yellow sandal" --output-path "messy_rooms_masks/large_corridor_100/blue and yellow sandal"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "blue and white striped towel" --output-path "messy_rooms_masks/large_corridor_100/blue and white striped towel"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "green plastic box" --output-path "messy_rooms_masks/large_corridor_100/green plastic box"
CUDA_VISIBLE_DEVICES=5 ns-render dataset --load-config outputs/large_corridor_100/lerf/2024-09-07_175211/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "red and blue doll" --output-path "messy_rooms_masks/large_corridor_100/red and blue doll"
                            


