# ns-render dataset --load-config outputs/ramen/lerf/2024-07-17_164600/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt chopsticks --output-path lerf_masks/ramen/chopsticks
# ns-render dataset --load-config outputs/ramen/lerf/2024-07-17_164600/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt egg --output-path lerf_masks/ramen/egg
# ns-render dataset --load-config outputs/ramen/lerf/2024-07-17_164600/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "glass of water" --output-path "lerf_masks/ramen/glass of water"
# ns-render dataset --load-config outputs/ramen/lerf/2024-07-17_164600/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "pork belly" --output-path "lerf_masks/ramen/pork belly"
# ns-render dataset --load-config outputs/ramen/lerf/2024-07-17_164600/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "wavy noodles in bowl" --output-path "lerf_masks/ramen/wavy noodles in bowl"
# ns-render dataset --load-config outputs/ramen/lerf/2024-07-17_164600/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "yellow bowl" --output-path "lerf_masks/ramen/yellow bowl"

ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which one is the chopstic on the side of yellow bowl" --output-path lerf_masks/ramen_reasoning/chopsticks
ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "what is the round, golden, protein-rich object in the bowl" --output-path lerf_masks/ramen_reasoning/egg
ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which one is a transparent cup with water in it" --output-path "lerf_masks/ramen_reasoning/glass of water"
ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the big piece of meat in the bowl" --output-path "lerf_masks/ramen_reasoning/pork belly"
ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which are long and thin noodles" --output-path "lerf_masks/ramen_reasoning/wavy noodles in bowl"
ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the yellow bowl used to hold noodles" --output-path "lerf_masks/ramen_reasoning/yellow bowl"
# ns-viewer --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml

