

# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt chopsticks --output-path lerf_masks/ramen/chopsticks
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt egg --output-path lerf_masks/ramen/egg
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "glass of water" --output-path "lerf_masks/ramen/glass of water"
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "pork belly" --output-path "lerf_masks/ramen/pork belly"
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "wavy noodles in bowl" --output-path "lerf_masks/ramen/wavy noodles in bowl"
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "yellow bowl" --output-path "lerf_masks/ramen/yellow bowl"



# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt chopsticks --output-path lerf_masks/ramen/chopsticks
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt egg --output-path lerf_masks/ramen/egg
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "glass of water" --output-path "lerf_masks/ramen/glass of water"
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "pork belly" --output-path "lerf_masks/ramen/pork belly"
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "wavy noodles in bowl" --output-path "lerf_masks/ramen/wavy noodles in bowl"
# ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "yellow bowl" --output-path "lerf_masks/ramen/yellow bowl"

CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which are used for eating Asian cuisine" --output-path lerf_masks/ramen_reasoning/chopsticks
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the round food item with a hard shell that is often boiled and served in a bowl" --output-path lerf_masks/ramen_reasoning/egg
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the clear liquid container that is often served alongside a meal" --output-path "lerf_masks/ramen_reasoning/glass of water"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the type of meat that is often served in a bowl with noodles and broth" --output-path "lerf_masks/ramen_reasoning/pork belly"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which are the long, thin, and wavy food items that are often served in a bowl with broth and meat" --output-path "lerf_masks/ramen_reasoning/wavy noodles in bowl"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_map_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the container that is often used to serve a hot and savory dish" --output-path "lerf_masks/ramen_reasoning/yellow bowl"

CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which are used for eating Asian cuisine" --output-path lerf_masks/ramen_reasoning/chopsticks
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the round food item with a hard shell that is often boiled and served in a bowl" --output-path lerf_masks/ramen_reasoning/egg
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the clear liquid container that is often served alongside a meal" --output-path "lerf_masks/ramen_reasoning/glass of water"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the type of meat that is often served in a bowl with noodles and broth" --output-path "lerf_masks/ramen_reasoning/pork belly"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which are the long, thin, and wavy food items that are often served in a bowl with broth and meat" --output-path "lerf_masks/ramen_reasoning/wavy noodles in bowl"
CUDA_VISIBLE_DEVICES=1 ns-render dataset --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml --rendered-output-names mask_0 --colormap-options.colormap turbo --colormap-options.colormap-min -1 --colormap-options.normalize True --text_prompt "which is the container that is often used to serve a hot and savory dish" --output-path "lerf_masks/ramen_reasoning/yellow bowl"

# ns-viewer --load-config outputs/ramen/lerf/2024-08-22_111856/config.yml

                               which are used for eating Asian cuisine",
                              "which is the round food item with a hard shell that is often boiled and served in a bowl",
                              "which is the clear liquid container that is often served alongside a meal",
                              "which is the type of meat that is often served in a bowl with noodles and broth",
                              "which are the long, thin, and wavy food items that are often served in a bowl with broth and meat",
                              "which is the container that is often used to serve a hot and savory dish